stages:
  - build
  - deploy

default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info

variables:
  DOCKER_HOST: tcp://docker:2375
  #
  # This instructs Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""


build-money-tracking-fe-alpha:
  image: docker:dind
  stage: build
  only:
    - /^money-tracking-fe-v\d+\.\d+\.\d+-alpha$/  # hanya jalankan pada tag dengan format money-tracking-fe-vx.y.z-alpha
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - TAG=$CI_COMMIT_TAG  # ambil bagian versi dari tag
    - DOCKER_TAG="$CI_REGISTRY_IMAGE:$TAG"
    - docker build --build-arg BACKEND_URL=$BACKEND_URL --build-arg SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN --build-arg NEXT_PUBLIC_REFRESH_TOKEN=$NEXT_PUBLIC_REFRESH_TOKEN -t $DOCKER_TAG .
    - docker push $DOCKER_TAG
    - docker tag $DOCKER_TAG $CI_REGISTRY_IMAGE:latest  # set versi terbaru
    - docker push $CI_REGISTRY_IMAGE:latest

deploy-money-tracking-frontend-alpha:
  stage: deploy
  image: alpine:latest
  only: 
    - /^money-tracking-fe-v\d+\.\d+\.\d+-alpha$/  # hanya jalankan pada tag dengan format money-tracking-fe-vx.y.z-alpha
  services:
    - name: docker:dind
      entrypoint: ["dockerd-entrypoint.sh", "--tls=false"]
  before_script:
    - 'which ssh-agent || ( apk update && apk add --no-cache openssh )'
    - mkdir -p ~/.ssh
    - echo "$SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh -o StrictHostKeyChecking=no $SSH_USER@$SERVER_RUNNER "export IMAGE='$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG' && docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY && echo $IMAGE && cd money-tracking/frontend && docker compose up -d --force-recreate && echo $IMAGE > test "
